version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: "postgres"
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@postgres.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    hostname: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always